### ISSUE TITLE
Is there a way to keep the Audio its currently playing or all of the Audio tracks?

### ISSUE THREAD

**Issue by ojoiP** [f0e/mpv-cut#1]
Hey, I like this fork a lot.

I have videos that have multiple audio tracks (6) but I would like to keep only track 2 of my audio during my cuts.

Is there anyway I can do this? ATM, it only keeps Audio 1 during the cuts and the rest gets deleted.

If I could keep the audio is currently playing during my cuts or all of them it would be great.

**Comment by f0e** [comment]
Sure, I've made the script now copy over all of the audio tracks when cutting.

**Comment by SimplisticGH** [comment]
This doesn't seem to be working anymore? I'm on mpv [v0.39.0](https://github.com/mpv-player/mpv/releases/tag/v0.39.0) and [v0.1.1](https://github.com/f0e/mpv-lossless-cut/releases/tag/v0.1.1)

Here's [a video for testing](https://files.catbox.moe/ncxvmj.mp4) if you need one

**Comment by f0e** [comment]
Fixed in https://github.com/f0e/mpv-lossless-cut/releases/tag/v0.1.2

**Comment by SimplisticGH** [comment]
Holy, thanks for the fast fix. This script has been invaluable for cleaning out my massive hoard of old obs replays.

**Comment by SimplisticGH** [comment]
Ah, shit... It seems the issue persists when doing merged cuts.

**Comment by f0e** [comment]
damn it, okay https://github.com/f0e/mpv-lossless-cut/releases/tag/v0.1.3 should be right

**Comment by SimplisticGH** [comment]
Yep, that fixed it. Thanks².
